// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/GreenOnGrey/hammurapi-core/internal/platform/acp (interfaces: AgentClient)
//
// Generated by this command:
//
//	mockgen -destination=mocks/agent.go -package=mocks . AgentClient
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	acp "github.com/GreenOnGrey/hammurapi-core/internal/platform/acp"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockAgentClient is a mock of AgentClient interface.
type MockAgentClient struct {
	ctrl     *gomock.Controller
	recorder *MockAgentClientMockRecorder
	isgomock struct{}
}

// MockAgentClientMockRecorder is the mock recorder for MockAgentClient.
type MockAgentClientMockRecorder struct {
	mock *MockAgentClient
}

// NewMockAgentClient creates a new mock instance.
func NewMockAgentClient(ctrl *gomock.Controller) *MockAgentClient {
	mock := &MockAgentClient{ctrl: ctrl}
	mock.recorder = &MockAgentClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAgentClient) EXPECT() *MockAgentClientMockRecorder {
	return m.recorder
}

// Cancel mocks base method.
func (m *MockAgentClient) Cancel(userID uuid.UUID) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Cancel", userID)
}

// Cancel indicates an expected call of Cancel.
func (mr *MockAgentClientMockRecorder) Cancel(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cancel", reflect.TypeOf((*MockAgentClient)(nil).Cancel), userID)
}

// CloseSession mocks base method.
func (m *MockAgentClient) CloseSession(userID uuid.UUID) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CloseSession", userID)
}

// CloseSession indicates an expected call of CloseSession.
func (mr *MockAgentClientMockRecorder) CloseSession(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseSession", reflect.TypeOf((*MockAgentClient)(nil).CloseSession), userID)
}

// Ensure mocks base method.
func (m *MockAgentClient) Ensure(ctx context.Context, userID uuid.UUID, setup func(acp.AgentCaps) acp.SessionSetup) (acp.SessionInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ensure", ctx, userID, setup)
	ret0, _ := ret[0].(acp.SessionInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Ensure indicates an expected call of Ensure.
func (mr *MockAgentClientMockRecorder) Ensure(ctx, userID, setup any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ensure", reflect.TypeOf((*MockAgentClient)(nil).Ensure), ctx, userID, setup)
}

// Prompt mocks base method.
func (m *MockAgentClient) Prompt(ctx context.Context, userID uuid.UUID, blocks []acp.ContentBlock, onUpdate func(acp.Update)) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Prompt", ctx, userID, blocks, onUpdate)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Prompt indicates an expected call of Prompt.
func (mr *MockAgentClientMockRecorder) Prompt(ctx, userID, blocks, onUpdate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Prompt", reflect.TypeOf((*MockAgentClient)(nil).Prompt), ctx, userID, blocks, onUpdate)
}
