// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/GreenOnGrey/hammurapi-core/internal/platform/git (interfaces: Provider,TokenSource)
//
// Generated by this command:
//
//	mockgen -destination=mocks/provider.go -package=mocks . Provider,TokenSource
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	http "net/http"
	reflect "reflect"

	git "github.com/GreenOnGrey/hammurapi-core/internal/platform/git"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockProvider is a mock of Provider interface.
type MockProvider struct {
	ctrl     *gomock.Controller
	recorder *MockProviderMockRecorder
	isgomock struct{}
}

// MockProviderMockRecorder is the mock recorder for MockProvider.
type MockProviderMockRecorder struct {
	mock *MockProvider
}

// NewMockProvider creates a new mock instance.
func NewMockProvider(ctrl *gomock.Controller) *MockProvider {
	mock := &MockProvider{ctrl: ctrl}
	mock.recorder = &MockProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProvider) EXPECT() *MockProviderMockRecorder {
	return m.recorder
}

// ApprovePR mocks base method.
func (m *MockProvider) ApprovePR(ctx context.Context, token string, number int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApprovePR", ctx, token, number)
	ret0, _ := ret[0].(error)
	return ret0
}

// ApprovePR indicates an expected call of ApprovePR.
func (mr *MockProviderMockRecorder) ApprovePR(ctx, token, number any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApprovePR", reflect.TypeOf((*MockProvider)(nil).ApprovePR), ctx, token, number)
}

// AuthCodeURL mocks base method.
func (m *MockProvider) AuthCodeURL(state, redirectURL string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AuthCodeURL", state, redirectURL)
	ret0, _ := ret[0].(string)
	return ret0
}

// AuthCodeURL indicates an expected call of AuthCodeURL.
func (mr *MockProviderMockRecorder) AuthCodeURL(state, redirectURL any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AuthCodeURL", reflect.TypeOf((*MockProvider)(nil).AuthCodeURL), state, redirectURL)
}

// BotToken mocks base method.
func (m *MockProvider) BotToken(ctx context.Context) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BotToken", ctx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BotToken indicates an expected call of BotToken.
func (mr *MockProviderMockRecorder) BotToken(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BotToken", reflect.TypeOf((*MockProvider)(nil).BotToken), ctx)
}

// BranchHead mocks base method.
func (m *MockProvider) BranchHead(ctx context.Context, token, branch string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BranchHead", ctx, token, branch)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BranchHead indicates an expected call of BranchHead.
func (mr *MockProviderMockRecorder) BranchHead(ctx, token, branch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BranchHead", reflect.TypeOf((*MockProvider)(nil).BranchHead), ctx, token, branch)
}

// ClosePR mocks base method.
func (m *MockProvider) ClosePR(ctx context.Context, token string, number int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClosePR", ctx, token, number)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClosePR indicates an expected call of ClosePR.
func (mr *MockProviderMockRecorder) ClosePR(ctx, token, number any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClosePR", reflect.TypeOf((*MockProvider)(nil).ClosePR), ctx, token, number)
}

// CommentPR mocks base method.
func (m *MockProvider) CommentPR(ctx context.Context, token string, number int, body string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CommentPR", ctx, token, number, body)
	ret0, _ := ret[0].(error)
	return ret0
}

// CommentPR indicates an expected call of CommentPR.
func (mr *MockProviderMockRecorder) CommentPR(ctx, token, number, body any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommentPR", reflect.TypeOf((*MockProvider)(nil).CommentPR), ctx, token, number, body)
}

// Commit mocks base method.
func (m *MockProvider) Commit(ctx context.Context, token, branch, message string, changes []git.FileChange) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Commit", ctx, token, branch, message, changes)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Commit indicates an expected call of Commit.
func (mr *MockProviderMockRecorder) Commit(ctx, token, branch, message, changes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Commit", reflect.TypeOf((*MockProvider)(nil).Commit), ctx, token, branch, message, changes)
}

// CommitParents mocks base method.
func (m *MockProvider) CommitParents(ctx context.Context, token, sha string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CommitParents", ctx, token, sha)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CommitParents indicates an expected call of CommitParents.
func (mr *MockProviderMockRecorder) CommitParents(ctx, token, sha any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitParents", reflect.TypeOf((*MockProvider)(nil).CommitParents), ctx, token, sha)
}

// CommitURL mocks base method.
func (m *MockProvider) CommitURL(sha string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CommitURL", sha)
	ret0, _ := ret[0].(string)
	return ret0
}

// CommitURL indicates an expected call of CommitURL.
func (mr *MockProviderMockRecorder) CommitURL(sha any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitURL", reflect.TypeOf((*MockProvider)(nil).CommitURL), sha)
}

// CreateBranch mocks base method.
func (m *MockProvider) CreateBranch(ctx context.Context, token, branch, fromSHA string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBranch", ctx, token, branch, fromSHA)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateBranch indicates an expected call of CreateBranch.
func (mr *MockProviderMockRecorder) CreateBranch(ctx, token, branch, fromSHA any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBranch", reflect.TypeOf((*MockProvider)(nil).CreateBranch), ctx, token, branch, fromSHA)
}

// CreateIssue mocks base method.
func (m *MockProvider) CreateIssue(ctx context.Context, token, title, body string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateIssue", ctx, token, title, body)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateIssue indicates an expected call of CreateIssue.
func (mr *MockProviderMockRecorder) CreateIssue(ctx, token, title, body any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateIssue", reflect.TypeOf((*MockProvider)(nil).CreateIssue), ctx, token, title, body)
}

// CreatePR mocks base method.
func (m *MockProvider) CreatePR(ctx context.Context, token, head, base, title, body string) (*git.PR, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePR", ctx, token, head, base, title, body)
	ret0, _ := ret[0].(*git.PR)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePR indicates an expected call of CreatePR.
func (mr *MockProviderMockRecorder) CreatePR(ctx, token, head, base, title, body any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePR", reflect.TypeOf((*MockProvider)(nil).CreatePR), ctx, token, head, base, title, body)
}

// CurrentUser mocks base method.
func (m *MockProvider) CurrentUser(ctx context.Context, token string) (*git.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CurrentUser", ctx, token)
	ret0, _ := ret[0].(*git.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CurrentUser indicates an expected call of CurrentUser.
func (mr *MockProviderMockRecorder) CurrentUser(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CurrentUser", reflect.TypeOf((*MockProvider)(nil).CurrentUser), ctx, token)
}

// DefaultBranch mocks base method.
func (m *MockProvider) DefaultBranch(ctx context.Context, token string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DefaultBranch", ctx, token)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DefaultBranch indicates an expected call of DefaultBranch.
func (mr *MockProviderMockRecorder) DefaultBranch(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DefaultBranch", reflect.TypeOf((*MockProvider)(nil).DefaultBranch), ctx, token)
}

// DeleteBranch mocks base method.
func (m *MockProvider) DeleteBranch(ctx context.Context, token, branch string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBranch", ctx, token, branch)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBranch indicates an expected call of DeleteBranch.
func (mr *MockProviderMockRecorder) DeleteBranch(ctx, token, branch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBranch", reflect.TypeOf((*MockProvider)(nil).DeleteBranch), ctx, token, branch)
}

// Exchange mocks base method.
func (m *MockProvider) Exchange(ctx context.Context, code, redirectURL string) (*git.Token, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exchange", ctx, code, redirectURL)
	ret0, _ := ret[0].(*git.Token)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exchange indicates an expected call of Exchange.
func (mr *MockProviderMockRecorder) Exchange(ctx, code, redirectURL any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exchange", reflect.TypeOf((*MockProvider)(nil).Exchange), ctx, code, redirectURL)
}

// ForRepo mocks base method.
func (m *MockProvider) ForRepo(repo string) git.Provider {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ForRepo", repo)
	ret0, _ := ret[0].(git.Provider)
	return ret0
}

// ForRepo indicates an expected call of ForRepo.
func (mr *MockProviderMockRecorder) ForRepo(repo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ForRepo", reflect.TypeOf((*MockProvider)(nil).ForRepo), repo)
}

// GetFile mocks base method.
func (m *MockProvider) GetFile(ctx context.Context, token, ref, path string) (*git.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFile", ctx, token, ref, path)
	ret0, _ := ret[0].(*git.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFile indicates an expected call of GetFile.
func (mr *MockProviderMockRecorder) GetFile(ctx, token, ref, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFile", reflect.TypeOf((*MockProvider)(nil).GetFile), ctx, token, ref, path)
}

// GetPR mocks base method.
func (m *MockProvider) GetPR(ctx context.Context, token string, number int) (*git.PRInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPR", ctx, token, number)
	ret0, _ := ret[0].(*git.PRInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPR indicates an expected call of GetPR.
func (mr *MockProviderMockRecorder) GetPR(ctx, token, number any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPR", reflect.TypeOf((*MockProvider)(nil).GetPR), ctx, token, number)
}

// GroupMembers mocks base method.
func (m *MockProvider) GroupMembers(ctx context.Context, token, group string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GroupMembers", ctx, token, group)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GroupMembers indicates an expected call of GroupMembers.
func (mr *MockProviderMockRecorder) GroupMembers(ctx, token, group any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GroupMembers", reflect.TypeOf((*MockProvider)(nil).GroupMembers), ctx, token, group)
}

// IsAncestor mocks base method.
func (m *MockProvider) IsAncestor(ctx context.Context, token, ancestor, descendant string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsAncestor", ctx, token, ancestor, descendant)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsAncestor indicates an expected call of IsAncestor.
func (mr *MockProviderMockRecorder) IsAncestor(ctx, token, ancestor, descendant any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsAncestor", reflect.TypeOf((*MockProvider)(nil).IsAncestor), ctx, token, ancestor, descendant)
}

// LatestCommit mocks base method.
func (m *MockProvider) LatestCommit(ctx context.Context, token, ref, path string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LatestCommit", ctx, token, ref, path)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LatestCommit indicates an expected call of LatestCommit.
func (mr *MockProviderMockRecorder) LatestCommit(ctx, token, ref, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LatestCommit", reflect.TypeOf((*MockProvider)(nil).LatestCommit), ctx, token, ref, path)
}

// ListFiles mocks base method.
func (m *MockProvider) ListFiles(ctx context.Context, token, ref, dir string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFiles", ctx, token, ref, dir)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFiles indicates an expected call of ListFiles.
func (mr *MockProviderMockRecorder) ListFiles(ctx, token, ref, dir any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFiles", reflect.TypeOf((*MockProvider)(nil).ListFiles), ctx, token, ref, dir)
}

// MergePR mocks base method.
func (m *MockProvider) MergePR(ctx context.Context, token string, number int, message string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MergePR", ctx, token, number, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// MergePR indicates an expected call of MergePR.
func (mr *MockProviderMockRecorder) MergePR(ctx, token, number, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MergePR", reflect.TypeOf((*MockProvider)(nil).MergePR), ctx, token, number, message)
}

// Name mocks base method.
func (m *MockProvider) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockProviderMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockProvider)(nil).Name))
}

// PRChangedFiles mocks base method.
func (m *MockProvider) PRChangedFiles(ctx context.Context, token string, number int) ([]git.ChangedFile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PRChangedFiles", ctx, token, number)
	ret0, _ := ret[0].([]git.ChangedFile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PRChangedFiles indicates an expected call of PRChangedFiles.
func (mr *MockProviderMockRecorder) PRChangedFiles(ctx, token, number any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PRChangedFiles", reflect.TypeOf((*MockProvider)(nil).PRChangedFiles), ctx, token, number)
}

// ParseHook mocks base method.
func (m *MockProvider) ParseHook(h http.Header, body []byte) (*git.HookEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseHook", h, body)
	ret0, _ := ret[0].(*git.HookEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseHook indicates an expected call of ParseHook.
func (mr *MockProviderMockRecorder) ParseHook(h, body any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseHook", reflect.TypeOf((*MockProvider)(nil).ParseHook), h, body)
}

// ParsePush mocks base method.
func (m *MockProvider) ParsePush(h http.Header, body []byte) (*git.PushEvent, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParsePush", h, body)
	ret0, _ := ret[0].(*git.PushEvent)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ParsePush indicates an expected call of ParsePush.
func (mr *MockProviderMockRecorder) ParsePush(h, body any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParsePush", reflect.TypeOf((*MockProvider)(nil).ParsePush), h, body)
}

// Refresh mocks base method.
func (m *MockProvider) Refresh(ctx context.Context, refreshToken string) (*git.Token, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Refresh", ctx, refreshToken)
	ret0, _ := ret[0].(*git.Token)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Refresh indicates an expected call of Refresh.
func (mr *MockProviderMockRecorder) Refresh(ctx, refreshToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Refresh", reflect.TypeOf((*MockProvider)(nil).Refresh), ctx, refreshToken)
}

// Repo mocks base method.
func (m *MockProvider) Repo() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Repo")
	ret0, _ := ret[0].(string)
	return ret0
}

// Repo indicates an expected call of Repo.
func (mr *MockProviderMockRecorder) Repo() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Repo", reflect.TypeOf((*MockProvider)(nil).Repo))
}

// RequestReview mocks base method.
func (m *MockProvider) RequestReview(ctx context.Context, token string, number int, reviewers []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RequestReview", ctx, token, number, reviewers)
	ret0, _ := ret[0].(error)
	return ret0
}

// RequestReview indicates an expected call of RequestReview.
func (mr *MockProviderMockRecorder) RequestReview(ctx, token, number, reviewers any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequestReview", reflect.TypeOf((*MockProvider)(nil).RequestReview), ctx, token, number, reviewers)
}

// RunPipeline mocks base method.
func (m *MockProvider) RunPipeline(ctx context.Context, token, workflow, ref string, params map[string]string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunPipeline", ctx, token, workflow, ref, params)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RunPipeline indicates an expected call of RunPipeline.
func (mr *MockProviderMockRecorder) RunPipeline(ctx, token, workflow, ref, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunPipeline", reflect.TypeOf((*MockProvider)(nil).RunPipeline), ctx, token, workflow, ref, params)
}

// SearchCode mocks base method.
func (m *MockProvider) SearchCode(ctx context.Context, token, query string) ([]git.SearchHit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchCode", ctx, token, query)
	ret0, _ := ret[0].([]git.SearchHit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchCode indicates an expected call of SearchCode.
func (mr *MockProviderMockRecorder) SearchCode(ctx, token, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchCode", reflect.TypeOf((*MockProvider)(nil).SearchCode), ctx, token, query)
}

// UpdatePRBranch mocks base method.
func (m *MockProvider) UpdatePRBranch(ctx context.Context, token string, number int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePRBranch", ctx, token, number)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePRBranch indicates an expected call of UpdatePRBranch.
func (mr *MockProviderMockRecorder) UpdatePRBranch(ctx, token, number any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePRBranch", reflect.TypeOf((*MockProvider)(nil).UpdatePRBranch), ctx, token, number)
}

// VerifyWebhook mocks base method.
func (m *MockProvider) VerifyWebhook(h http.Header, body []byte, secret string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyWebhook", h, body, secret)
	ret0, _ := ret[0].(bool)
	return ret0
}

// VerifyWebhook indicates an expected call of VerifyWebhook.
func (mr *MockProviderMockRecorder) VerifyWebhook(h, body, secret any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyWebhook", reflect.TypeOf((*MockProvider)(nil).VerifyWebhook), h, body, secret)
}

// MockTokenSource is a mock of TokenSource interface.
type MockTokenSource struct {
	ctrl     *gomock.Controller
	recorder *MockTokenSourceMockRecorder
	isgomock struct{}
}

// MockTokenSourceMockRecorder is the mock recorder for MockTokenSource.
type MockTokenSourceMockRecorder struct {
	mock *MockTokenSource
}

// NewMockTokenSource creates a new mock instance.
func NewMockTokenSource(ctrl *gomock.Controller) *MockTokenSource {
	mock := &MockTokenSource{ctrl: ctrl}
	mock.recorder = &MockTokenSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenSource) EXPECT() *MockTokenSourceMockRecorder {
	return m.recorder
}

// Token mocks base method.
func (m *MockTokenSource) Token(ctx context.Context, userID uuid.UUID) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Token", ctx, userID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Token indicates an expected call of Token.
func (mr *MockTokenSourceMockRecorder) Token(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Token", reflect.TypeOf((*MockTokenSource)(nil).Token), ctx, userID)
}
