// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/GreenOnGrey/hammurapi-core/internal/specdata (interfaces: Store)
//
// Generated by this command:
//
//	mockgen -destination=mocks/store.go -package=mocks . Store
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/GreenOnGrey/hammurapi-core/internal/domain"
	httpx "github.com/GreenOnGrey/hammurapi-core/internal/platform/httpx"
	postgres "github.com/GreenOnGrey/hammurapi-core/internal/platform/postgres"
	specdata "github.com/GreenOnGrey/hammurapi-core/internal/specdata"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
	isgomock struct{}
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// AcquireLock mocks base method.
func (m *MockStore) AcquireLock(ctx context.Context, featureID, userID uuid.UUID) (*specdata.Lock, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AcquireLock", ctx, featureID, userID)
	ret0, _ := ret[0].(*specdata.Lock)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// AcquireLock indicates an expected call of AcquireLock.
func (mr *MockStoreMockRecorder) AcquireLock(ctx, featureID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AcquireLock", reflect.TypeOf((*MockStore)(nil).AcquireLock), ctx, featureID, userID)
}

// ActiveGate mocks base method.
func (m *MockStore) ActiveGate(ctx context.Context, featureID uuid.UUID, area domain.Area) (*specdata.Gate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ActiveGate", ctx, featureID, area)
	ret0, _ := ret[0].(*specdata.Gate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ActiveGate indicates an expected call of ActiveGate.
func (mr *MockStoreMockRecorder) ActiveGate(ctx, featureID, area any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ActiveGate", reflect.TypeOf((*MockStore)(nil).ActiveGate), ctx, featureID, area)
}

// ActiveGates mocks base method.
func (m *MockStore) ActiveGates(ctx context.Context, featureID uuid.UUID) ([]specdata.Gate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ActiveGates", ctx, featureID)
	ret0, _ := ret[0].([]specdata.Gate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ActiveGates indicates an expected call of ActiveGates.
func (mr *MockStoreMockRecorder) ActiveGates(ctx, featureID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ActiveGates", reflect.TypeOf((*MockStore)(nil).ActiveGates), ctx, featureID)
}

// DropLock mocks base method.
func (m *MockStore) DropLock(ctx context.Context, featureID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DropLock", ctx, featureID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DropLock indicates an expected call of DropLock.
func (mr *MockStoreMockRecorder) DropLock(ctx, featureID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DropLock", reflect.TypeOf((*MockStore)(nil).DropLock), ctx, featureID)
}

// FeatureByID mocks base method.
func (m *MockStore) FeatureByID(ctx context.Context, id uuid.UUID) (*specdata.Feature, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FeatureByID", ctx, id)
	ret0, _ := ret[0].(*specdata.Feature)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FeatureByID indicates an expected call of FeatureByID.
func (mr *MockStoreMockRecorder) FeatureByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FeatureByID", reflect.TypeOf((*MockStore)(nil).FeatureByID), ctx, id)
}

// FeatureByUniqueID mocks base method.
func (m *MockStore) FeatureByUniqueID(ctx context.Context, uniqueID string) (*specdata.Feature, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FeatureByUniqueID", ctx, uniqueID)
	ret0, _ := ret[0].(*specdata.Feature)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FeatureByUniqueID indicates an expected call of FeatureByUniqueID.
func (mr *MockStoreMockRecorder) FeatureByUniqueID(ctx, uniqueID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FeatureByUniqueID", reflect.TypeOf((*MockStore)(nil).FeatureByUniqueID), ctx, uniqueID)
}

// FeatureIssueKeys mocks base method.
func (m *MockStore) FeatureIssueKeys(ctx context.Context, featureID uuid.UUID) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FeatureIssueKeys", ctx, featureID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FeatureIssueKeys indicates an expected call of FeatureIssueKeys.
func (mr *MockStoreMockRecorder) FeatureIssueKeys(ctx, featureID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FeatureIssueKeys", reflect.TypeOf((*MockStore)(nil).FeatureIssueKeys), ctx, featureID)
}

// FeaturesPendingCleanup mocks base method.
func (m *MockStore) FeaturesPendingCleanup(ctx context.Context) ([]specdata.Feature, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FeaturesPendingCleanup", ctx)
	ret0, _ := ret[0].([]specdata.Feature)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FeaturesPendingCleanup indicates an expected call of FeaturesPendingCleanup.
func (mr *MockStoreMockRecorder) FeaturesPendingCleanup(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FeaturesPendingCleanup", reflect.TypeOf((*MockStore)(nil).FeaturesPendingCleanup), ctx)
}

// Fixes mocks base method.
func (m *MockStore) Fixes(ctx context.Context, parentID uuid.UUID) ([]specdata.FeatureRef, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Fixes", ctx, parentID)
	ret0, _ := ret[0].([]specdata.FeatureRef)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Fixes indicates an expected call of Fixes.
func (mr *MockStoreMockRecorder) Fixes(ctx, parentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Fixes", reflect.TypeOf((*MockStore)(nil).Fixes), ctx, parentID)
}

// GetLock mocks base method.
func (m *MockStore) GetLock(ctx context.Context, featureID uuid.UUID) (*specdata.Lock, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLock", ctx, featureID)
	ret0, _ := ret[0].(*specdata.Lock)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLock indicates an expected call of GetLock.
func (mr *MockStoreMockRecorder) GetLock(ctx, featureID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLock", reflect.TypeOf((*MockStore)(nil).GetLock), ctx, featureID)
}

// History mocks base method.
func (m *MockStore) History(ctx context.Context, featureID uuid.UUID, area domain.Area, page httpx.Page) ([]specdata.GateEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "History", ctx, featureID, area, page)
	ret0, _ := ret[0].([]specdata.GateEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// History indicates an expected call of History.
func (mr *MockStoreMockRecorder) History(ctx, featureID, area, page any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "History", reflect.TypeOf((*MockStore)(nil).History), ctx, featureID, area, page)
}

// InTx mocks base method.
func (m *MockStore) InTx(ctx context.Context, fn func(specdata.Store) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InTx", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// InTx indicates an expected call of InTx.
func (mr *MockStoreMockRecorder) InTx(ctx, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InTx", reflect.TypeOf((*MockStore)(nil).InTx), ctx, fn)
}

// InsertEvent mocks base method.
func (m *MockStore) InsertEvent(ctx context.Context, e *specdata.GateEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertEvent", ctx, e)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertEvent indicates an expected call of InsertEvent.
func (mr *MockStoreMockRecorder) InsertEvent(ctx, e any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertEvent", reflect.TypeOf((*MockStore)(nil).InsertEvent), ctx, e)
}

// InsertFeature mocks base method.
func (m *MockStore) InsertFeature(ctx context.Context, f *specdata.Feature) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertFeature", ctx, f)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertFeature indicates an expected call of InsertFeature.
func (mr *MockStoreMockRecorder) InsertFeature(ctx, f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertFeature", reflect.TypeOf((*MockStore)(nil).InsertFeature), ctx, f)
}

// InsertGate mocks base method.
func (m *MockStore) InsertGate(ctx context.Context, g *specdata.Gate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertGate", ctx, g)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertGate indicates an expected call of InsertGate.
func (mr *MockStoreMockRecorder) InsertGate(ctx, g any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertGate", reflect.TypeOf((*MockStore)(nil).InsertGate), ctx, g)
}

// LastSubmitter mocks base method.
func (m *MockStore) LastSubmitter(ctx context.Context, gateID uuid.UUID) (*uuid.UUID, *string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LastSubmitter", ctx, gateID)
	ret0, _ := ret[0].(*uuid.UUID)
	ret1, _ := ret[1].(*string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// LastSubmitter indicates an expected call of LastSubmitter.
func (mr *MockStoreMockRecorder) LastSubmitter(ctx, gateID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LastSubmitter", reflect.TypeOf((*MockStore)(nil).LastSubmitter), ctx, gateID)
}

// LinkIssue mocks base method.
func (m *MockStore) LinkIssue(ctx context.Context, featureID, issueID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LinkIssue", ctx, featureID, issueID)
	ret0, _ := ret[0].(error)
	return ret0
}

// LinkIssue indicates an expected call of LinkIssue.
func (mr *MockStoreMockRecorder) LinkIssue(ctx, featureID, issueID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LinkIssue", reflect.TypeOf((*MockStore)(nil).LinkIssue), ctx, featureID, issueID)
}

// ListFeatures mocks base method.
func (m *MockStore) ListFeatures(ctx context.Context, f specdata.ListFilter) ([]specdata.ListedFeature, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFeatures", ctx, f)
	ret0, _ := ret[0].([]specdata.ListedFeature)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFeatures indicates an expected call of ListFeatures.
func (mr *MockStoreMockRecorder) ListFeatures(ctx, f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFeatures", reflect.TypeOf((*MockStore)(nil).ListFeatures), ctx, f)
}

// MarkDeleted mocks base method.
func (m *MockStore) MarkDeleted(ctx context.Context, id, by uuid.UUID, cleanupPending bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkDeleted", ctx, id, by, cleanupPending)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkDeleted indicates an expected call of MarkDeleted.
func (mr *MockStoreMockRecorder) MarkDeleted(ctx, id, by, cleanupPending any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkDeleted", reflect.TypeOf((*MockStore)(nil).MarkDeleted), ctx, id, by, cleanupPending)
}

// MarkWebhookProcessed mocks base method.
func (m *MockStore) MarkWebhookProcessed(ctx context.Context, eventID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkWebhookProcessed", ctx, eventID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarkWebhookProcessed indicates an expected call of MarkWebhookProcessed.
func (mr *MockStoreMockRecorder) MarkWebhookProcessed(ctx, eventID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkWebhookProcessed", reflect.TypeOf((*MockStore)(nil).MarkWebhookProcessed), ctx, eventID)
}

// NextNumber mocks base method.
func (m *MockStore) NextNumber(ctx context.Context, systemID uuid.UUID) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NextNumber", ctx, systemID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NextNumber indicates an expected call of NextNumber.
func (mr *MockStoreMockRecorder) NextNumber(ctx, systemID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NextNumber", reflect.TypeOf((*MockStore)(nil).NextNumber), ctx, systemID)
}

// PeekNumber mocks base method.
func (m *MockStore) PeekNumber(ctx context.Context, systemID uuid.UUID) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PeekNumber", ctx, systemID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PeekNumber indicates an expected call of PeekNumber.
func (mr *MockStoreMockRecorder) PeekNumber(ctx, systemID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PeekNumber", reflect.TypeOf((*MockStore)(nil).PeekNumber), ctx, systemID)
}

// Q mocks base method.
func (m *MockStore) Q() postgres.Querier {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Q")
	ret0, _ := ret[0].(postgres.Querier)
	return ret0
}

// Q indicates an expected call of Q.
func (mr *MockStoreMockRecorder) Q() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Q", reflect.TypeOf((*MockStore)(nil).Q))
}

// ReleaseLock mocks base method.
func (m *MockStore) ReleaseLock(ctx context.Context, featureID, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReleaseLock", ctx, featureID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReleaseLock indicates an expected call of ReleaseLock.
func (mr *MockStoreMockRecorder) ReleaseLock(ctx, featureID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReleaseLock", reflect.TypeOf((*MockStore)(nil).ReleaseLock), ctx, featureID, userID)
}

// SaveGate mocks base method.
func (m *MockStore) SaveGate(ctx context.Context, g *specdata.Gate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveGate", ctx, g)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveGate indicates an expected call of SaveGate.
func (mr *MockStoreMockRecorder) SaveGate(ctx, g any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveGate", reflect.TypeOf((*MockStore)(nil).SaveGate), ctx, g)
}

// SetBranchCleanupPending mocks base method.
func (m *MockStore) SetBranchCleanupPending(ctx context.Context, id uuid.UUID, pending bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetBranchCleanupPending", ctx, id, pending)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetBranchCleanupPending indicates an expected call of SetBranchCleanupPending.
func (mr *MockStoreMockRecorder) SetBranchCleanupPending(ctx, id, pending any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetBranchCleanupPending", reflect.TypeOf((*MockStore)(nil).SetBranchCleanupPending), ctx, id, pending)
}

// SetFlagKey mocks base method.
func (m *MockStore) SetFlagKey(ctx context.Context, id uuid.UUID, flag *string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetFlagKey", ctx, id, flag)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetFlagKey indicates an expected call of SetFlagKey.
func (mr *MockStoreMockRecorder) SetFlagKey(ctx, id, flag any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetFlagKey", reflect.TypeOf((*MockStore)(nil).SetFlagKey), ctx, id, flag)
}

// SetImportItem mocks base method.
func (m *MockStore) SetImportItem(ctx context.Context, importID uuid.UUID, archiveID, status string, featureID *uuid.UUID, errText *string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetImportItem", ctx, importID, archiveID, status, featureID, errText)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetImportItem indicates an expected call of SetImportItem.
func (mr *MockStoreMockRecorder) SetImportItem(ctx, importID, archiveID, status, featureID, errText any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetImportItem", reflect.TypeOf((*MockStore)(nil).SetImportItem), ctx, importID, archiveID, status, featureID, errText)
}

// SetPhase mocks base method.
func (m *MockStore) SetPhase(ctx context.Context, id uuid.UUID, phase domain.FeaturePhase) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetPhase", ctx, id, phase)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetPhase indicates an expected call of SetPhase.
func (mr *MockStoreMockRecorder) SetPhase(ctx, id, phase any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPhase", reflect.TypeOf((*MockStore)(nil).SetPhase), ctx, id, phase)
}

// SystemByKeys mocks base method.
func (m *MockStore) SystemByKeys(ctx context.Context, domainKey, systemKey string) (*specdata.System, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SystemByKeys", ctx, domainKey, systemKey)
	ret0, _ := ret[0].(*specdata.System)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SystemByKeys indicates an expected call of SystemByKeys.
func (mr *MockStoreMockRecorder) SystemByKeys(ctx, domainKey, systemKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SystemByKeys", reflect.TypeOf((*MockStore)(nil).SystemByKeys), ctx, domainKey, systemKey)
}

// UserIDByUsername mocks base method.
func (m *MockStore) UserIDByUsername(ctx context.Context, username string) (*uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserIDByUsername", ctx, username)
	ret0, _ := ret[0].(*uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UserIDByUsername indicates an expected call of UserIDByUsername.
func (mr *MockStoreMockRecorder) UserIDByUsername(ctx, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserIDByUsername", reflect.TypeOf((*MockStore)(nil).UserIDByUsername), ctx, username)
}
